# Default values for slurm-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: harbor.apulis.cn:8443/operator/slurm-operator
  tag: v1.0.0