apiVersion: slurmoperator.apulis.cn/v1beta1
kind: SlurmApplication
metadata:
  name: slurmapplication-sample
spec:
  jupyter:
    image: rancavil/slurm-jupyter:19.05.5-1
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "500Mi"
    labels:
      test: "3"
    nodeSelector:
      kubernetes.io/role: "master"
  master:
    image: rancavil/slurm-master:19.05.5-1
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "2"
        memory: "2Gi"
    labels:
      test: "3"
  node:
    image: rancavil/slurm-node:19.05.5-1
    instance: 4
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "2"
        memory: "2Gi"
    labels:
      test: "3"